# Generated by Django 3.1.7 on 2021-03-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
